version: '2'
services:
    app:
        build: .
        image: user/contraoferta
        ports: 
            - "9000:9000"
        depends_on: 
            - db
        environment: 
            - SPRING_PROFILES_ACTIVE=prod
    
    db:
        image: postgres:10
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_PASSWORD=postgresql
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres